export const DEFAULT_OPTIONS = {
  debug: false,
  demoteHeadings: true,
  folder: undefined,
  target: "googledocs-output/_guide-pages",
  imagesTarget: "googledocs-output/assets/images/_guide-pages",
  imagesOptions: undefined,
  keepDefaultStyle: false,
  pageContext: [],
  skipCodes: false,
  skipFootnotes: false,
  skipHeadings: false,
  skipImages: false,
  skipLists: false,
  skipQuotes: false,
  skipTables: false,
};
